### ISSUE TITLE
volume control visually obstructed and not functioning

### ISSUE THREAD

**Issue by inieves** [dtseto/Hermes-master#6]
see attached image.
clicking/dragging slider does noting

<img width="246" alt="Screenshot 2024-11-22 at 3 51 26 PM" src="https://github.com/user-attachments/assets/c5db9521-0131-4ba8-b611-607558bb77ba">

**Comment by pfahlstrom** [comment]
Interesting. I don't have that error on my copy of beta 5.

**Comment by dtseto** [comment]
> see attached image. clicking/dragging slider does noting
> 
> <img alt="Screenshot 2024-11-22 at 3 51 26 PM" width="246" src="https://private-user-images.githubusercontent.com/656250/389101199-c5db9521-0131-4ba8-b611-607558bb77ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTc5NjQsIm5iZiI6MTczMjMxNzY2NCwicGF0aCI6Ii82NTYyNTAvMzg5MTAxMTk5LWM1ZGI5NTIxLTAxMzEtNGJhOC1iNjExLTYwNzU1OGJiNzdiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQyMzIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTg0ZDBiZjg0NDA0N2FlZTUzNDU5NTRkNGQ1YzA1NzNlZWIyYThiMmJiOGI2ZDMwZGI3ZDI4YWUxNzA3YjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oW4lRZ_No7bGM5e2IkRYFt0NZuAZavMchVLlmoMWMe0">

Thanks I updated a new build just now with added constraints which should fix some of that. If it still doesn't work can you can load it in terminal and see if there any debug messages.

**Comment by inieves** [comment]
After latest update I see this.

Also I noticed the 2 audio streams playing at same time, that was discussed in some of the last messages.

<img width="257" alt="Screenshot 2024-11-22 at 7 12 49 PM" src="https://github.com/user-attachments/assets/69d62a4b-024c-4d65-ab90-6a4bb42b2158">

**Comment by dtseto** [comment]
> After latest update I see this.
> 
> 
> 
> Also I noticed the 2 audio streams playing at same time, that was discussed in some of the last messages.
> 
> 
> 
> <img width="257" alt="Screenshot 2024-11-22 at 7 12 49 PM" src="https://github.com/user-attachments/assets/69d62a4b-024c-4d65-ab90-6a4bb42b2158">
> 
> 

Can you try different stations and songs and see if the explanations appear. Not all of them have the explanations.

Also the station modes don't appear till you press the plus sign and some of the smaller custom stations may not support them.

Let me look into the two streams. Thanks for testing it.

**Comment by inieves** [comment]
I am able to get explanations to appear.

I am not able to get anything to happen with the plus/minus signs.  Also, I am not really sure what “station modes” are.

**Comment by dtseto** [comment]
It changes the mix of your station between more popular related songs versus less popular related songs. It is one of the last newer features I want to release before refactoring and updating the app to require mac os 11+ from the present 10.10.

Explanation is below

https://help.pandora.com/s/article/Pandora-Modes?language=en_US

Does the volume work correctly and is unobstructed with the patched one?

**Comment by dtseto** [comment]
Appreciate it. I just uploaded new build with some fixes to ui obstruction a few days ago by adding constraints for apple silicon. Also made some changes to reduce likelihood of double streaming and others to station mode errors. 

> see attached image. clicking/dragging slider does noting
> 
> <img alt="Screenshot 2024-11-22 at 3 51 26 PM" width="246" src="https://private-user-images.githubusercontent.com/656250/389101199-c5db9521-0131-4ba8-b611-607558bb77ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDkyNzcsIm5iZiI6MTczMjY0ODk3NywicGF0aCI6Ii82NTYyNTAvMzg5MTAxMTk5LWM1ZGI5NTIxLTAxMzEtNGJhOC1iNjExLTYwNzU1OGJiNzdiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxOTIyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODI0NmIwMjg5ZDk1YjJmZTIwNjAzN2M5OWU3NGZhZTQ4ZTU3MzY0ZDJjYzc2ZDM2ZGViOTE4YTBkZmMyYzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WbGPbDFmOaFPRpx6Q_SChJi6rUm19L-a_WyryRyBy3E">

**Comment by dtseto** [comment]
Got an apple silicon Mac running 15.1 for testing. 

1.32b4 is the most stable it includes the genome project song data but does not include station modes. Also fixed the UI bugs. It's in a release for download. Am rewriting it for later macOS versions and removing the deprecated legacy code right now before adding back the station modes.

<img width="469" alt="image" src="https://github.com/user-attachments/assets/5e6a6ef7-54e1-45ab-8aec-fcdc0c2c2778" /> 1.32b4 with ui fixes on apple silicon 15.1


> see attached image. clicking/dragging slider does noting
> 
> <img alt="Screenshot 2024-11-22 at 3 51 26 PM" width="246" src="https://private-user-images.githubusercontent.com/656250/389101199-c5db9521-0131-4ba8-b611-607558bb77ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNDg2MTIsIm5iZiI6MTczNDA0ODMxMiwicGF0aCI6Ii82NTYyNTAvMzg5MTAxMTk5LWM1ZGI5NTIxLTAxMzEtNGJhOC1iNjExLTYwNzU1OGJiNzdiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QwMDA1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzFlNDZjMmFjZjA1MTdlNzUyNDQ2MGI1YzA2YzA4MDVkNTM3ZTQ3OTE0ZWEzY2M1ZGQ0ZThjMzY1YmZkNjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LgW48TFv6yosJvihyvHshe3TqFp8CgnhHShzaZ8Bx88">
